# Generated by Django 5.0.7 on 2024-08-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident_name",
                    models.CharField(max_length=500, verbose_name="Incident Name"),
                ),
                ("date_of_incident", models.DateField(verbose_name="Date of Incident")),
                (
                    "incident_priority",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        max_length=6,
                        verbose_name="Incident Priority",
                    ),
                ),
                (
                    "time_of_occurrence",
                    models.TimeField(verbose_name="Time Incident Occurred"),
                ),
                (
                    "time_of_resolution",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Time Incident Was Resolved"
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[("Malware", "Malware")],
                        max_length=50,
                        verbose_name="Incident Type",
                    ),
                ),
                (
                    "personnel_involved",
                    models.TextField(
                        blank=True, null=True, verbose_name="Personnel Involved"
                    ),
                ),
                (
                    "incident_impact",
                    models.TextField(
                        blank=True, null=True, verbose_name="Incident Impact"
                    ),
                ),
                (
                    "brief_summary",
                    models.TextField(
                        blank=True, null=True, verbose_name="Brief Summary"
                    ),
                ),
            ],
        ),
    ]
