# Generated by Django 5.0.7 on 2024-08-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='is_editable',
            field=models.BooleanField(default=True),
        ),
    ]
