# Generated by Django 5.0.7 on 2024-09-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_task_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Todo', 'Todo'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Todo', max_length=20),
        ),
    ]
