# Generated by Django 5.0.7 on 2024-10-01 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0009_retrospective_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='related_incidents',
        ),
    ]
