# Generated by Django 5.0.7 on 2024-10-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0010_remove_incident_related_incidents'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='related_incidents',
            field=models.ManyToManyField(blank=True, to='incidents.incident'),
        ),
    ]
