# Generated by Django 5.0.7 on 2024-10-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0011_incident_related_incidents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrospectivetemplate',
            name='content',
            field=models.JSONField(),
        ),
    ]
